name: weatherapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  lottie: ^2.6.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/sunny.png
    - assets/images/winter.jpg
    - assets/images/city.jpg
    - assets/images/snow.jpg
    - assets/images/cloudy.jpg
    - assets/images/cloiud_animation.json
  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900